# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c49ef01d4a9ab1f1be2ee5924e798e79880444346f74cf1dd6f689556c1c89f670c2675ca8c9d8b1925c1c609bcea0adf29e98660f9182ac33b532fff8e60b0

test:
  secret_key_base: d5723936fd8aed3534ee68ddef331fdffc15b89192a6773b78617edbc77b777ad716b203a34224da4c4d9425730c9f90c16fa455e246a04002d6acab339806e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
